@echo off
@rem  Autogenerated by 'obfuscated_sshd.sh win32'
title Proxy_g_f_w_l_x_l For Windows
:orz
ping   255.255.255.255 -n 5
plonk "255.255.255.255" -C -N -D 7070 -ssh -2 -P 0000 -Z strX -l userX -pw "ZZZZ" -i gfw.win32 -v
goto orz

